# Generated by Django 4.2 on 2023-06-02 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cyroombase', '0005_remove_question_downvotes_remove_question_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvoted_users',
            field=models.ManyToManyField(related_name='upvoted_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
